### ISSUE TITLE
Puzzle mode crashes when I rotate to landscape mode

### ISSUE THREAD

**Issue by peti** [jcarolus/android-chess#10]
First of all, thanks for the awesome app! I really love it.

I've noticed that I can reliably crash the app when I start the puzzles in portrait mode, and then rotate the phone to landscape. The app is just gone. This happens with both my Cyanogen 11 (KitKat) HTC One XL and my Kindle Fire tablet. Other parts of the app don't seem to have that problem, though.

**Comment by jcarolus** [comment]
Fixed
