### ISSUE TITLE
board color contrast reduction makes for difficulty playing games

### ISSUE THREAD

**Issue by smemsh** [jcarolus/android-chess#102]
with the latest update, the blue board changed.  I find the new color to be difficult to play on due to low contrast.  I cannot tell how it changed because I don't have an older copy.  I think the blue/white was changed to dark-blue/light-blue, or possibly the two blues were made closer to each other.  This new board is more difficult to play with.  Could it be changed back? Was this change intentional?

**Comment by TimmyT123** [comment]
Yes.  I believe the darker color was made lighter, so the dots stick out more.  The colors may be different on different devices.  It is probably best to let the user choose the colors.  It will be fixed on the next update.  Thanks for letting us know.

**Comment by smemsh** [comment]
Looks like the beta fixes this.  I believe the original blue has been restored and I see the new color picker that allows custom colors.  So I'm going to go ahead and close this.  Thanks!
