### ISSUE TITLE
Some way to disable/hide chat

### ISSUE THREAD

**Issue by luke-jr** [jcarolus/android-chess#111]
I'd like to disable/hide the chat entirely on my children's phones. My ideal solution is a config file I can set a flag in over SSH. :)

In the meantime, I have a server that proxies to freechess.org and strips out chat messages... it'd be simpler to do this if there was a way to configure the server besides vim'ing random binaries.

**Comment by jcarolus** [comment]
Some sort of parental-pin setting when logging in on freechess could be an idea?

**Comment by luke-jr** [comment]
I don't know what "parental-pin" means. I want them to be able to play (at least with each other) online, just not see chat messages.

**Comment by jcarolus** [comment]
chat should be completely hidden (even from console) with latest release.
