### ISSUE TITLE
Add F-Droid build flavour sans Google Play services

### ISSUE THREAD

**Issue by Matrixcoffee** [jcarolus/android-chess#112]
Greetings!

Once upon a time, Chess was part of the F-Droid repository. Unfortunately the inclusion of Google Play services means that the app can no longer be updated, and is now several years out of date.

If in any way possible, please add a build flavour which excludes Google Play services, and other non-FOSS libraries if any, so that us F-Droid users can again enjoy the latest version of Chess.

Kind regards,
Coffee

**Comment by Asara** [comment]
I would like to second this request.  The latest version on F-Droid is from 08/2014.  

Big fan of Chess and woule love the latest and greatest!

**Comment by jcarolus** [comment]
Hi,
I would welcome and merge a pull request containing a build flavour that does this.
Currently I do not have the priority on Chess to investigate and do this myself.

Best regards,
Jeroen

**Comment by IzzySoft** [comment]
We still have [this issue](https://gitlab.com/fdroid/fdroiddata/issues/790) open at F-Droid. Is there any chance we get this solved – or must we really give up on it? I saw new commits, so I was hoping… ?

**Comment by jcarolus** [comment]
Hi @IzzySoft please have a look at #128 , it adds a product flavour 'foss'. 
Can you let me know if this is usable on your end?

**Comment by IzzySoft** [comment]
Thanks! I'm not an Android dev; but from what I understand, the `build.gradle` should fit. Let me know when it's merged, so I can ping a packager to take a closer look (and give it a try).

**Comment by jcarolus** [comment]
@IzzySoft 
It's merged. Also released, v8.9.4
Cheers,
Jeroen

**Comment by IzzySoft** [comment]
Thanks! Ping sent.

**Comment by jcarolus** [comment]
@IzzySoft can I close the issue? I did not find Chess in f-droid yet, but it seems like it's closed on your side.

**Comment by IzzySoft** [comment]
Metadata were updated 5 days ago, but there was not yet an index release since (which is why you cannot yet see the new version in the repo). As this issue was about adding a build flavor, and that obviously has been done, I'd say go ahead and close it. I hope there will be an index run soon (usually happens at least once a week, but currently there seem to be updates to the server which might relay that a bit), and the effects will become visible.

Thanks!
