### ISSUE TITLE
Game sound settings can't be deactivated

### ISSUE THREAD

**Issue by jubreal** [jcarolus/android-chess#116]
The user “no sound” settings option should be retained and not forcefully return to “default sound” settings while playing the game.

#### Actual behavior
The settings keep returning forcefully to “default sound” after setting it to “none” which means no sound.

#### How to reproduce
1.	Install app from playstore
2.	Click on “Global settings” on th app homepage
3.	Click on Sound
4.	Select “none” from the notification tone options and click ok
5.	Return to the app homepage
6.	Repeats steps 2 and 3.
It will be observed that the settings is back on “default ringtone” and the user settings is not enabled.

* Browser/App version: Chess version 8.8.3
*Operating system: Android 6.0

#### Recording Of The Bug

https://youtu.be/SvA1IaUftJk

**Comment by jcarolus** [comment]
This one should also be fixed, and a "switch" is available next to the board for quick on/off.
