### ISSUE TITLE
Game time doesn't reset when new game is started.

### ISSUE THREAD

**Issue by jubreal** [jcarolus/android-chess#117]
#### Expected behavior
The game time of each player should reset to the default game time that was set for each game everytime a new game is started.

#### Actual behavior
The game time does not reset and continue to countdown from the old game time even when chess piece colour are changed between players.

#### How to reproduce
1.	Install app from playstore
2.	Click on play 
3.	Click on the settings icon slider (3 dots beside option) at the top right corner.
4.	Click on “set clock” and select any time apart from no clock option
5.	Play the game for some time
6.	Click on icon “new” among the icons present at the bottom of the chess board and click ok to reset the game (you may decide to change some options such as chess piece colour for easier spotting)

It will be observed that the even though the game has been reset, the time from the previous /old game was retained. Hence,the bug.

* Browser/App version: Chess version 8.8.3
*Operating system: Android 6.0

#### Recording Of The Bug

https://youtu.be/HDIlfhuS24Y

**Comment by jcarolus** [comment]
This should finally be fixed now, thanks for posting.
