### ISSUE TITLE
Sub controls settings options are missing in landscape mode

### ISSUE THREAD

**Issue by jubreal** [jcarolus/android-chess#119]
#### Expected behavior
The game options should be fully accessible both in portrait and landscape mode since the app supports both functionality.

#### Actual behavior
The game subcontrol settings can’t be accessed or used when playing game in landscape mode.

#### How to reproduce
1.	Install app from playstore
2.	Click on play 
3.	Rotate phone to landscape mode
4.	Click on the “sub control settings” icon, the 
It will be observed that the drop down options which are present in portrait mode are absent in landscape mode. Hence, the bug.

* Browser/App version: Chess version 8.8.3
*Operating system: Android 6.0

#### Recording Of The Bug

https://youtu.be/uHZV8-sT9Hg

**Comment by jcarolus** [comment]
Thanks for posting the issue.
In a future release, all landscape views will be removed, making it a portrait only app. This is probably not the resolution you were looking for, but this is a choice made to make maintenance of the project more manageable.
