### ISSUE TITLE
Groovy SDK has changed. 

### ISSUE THREAD

**Issue by vvlabs** [jcarolus/android-chess#124]
I'm getting this error when i'm trying to build to test: 
Could not find org.codehaus.groovy:groovy-all:2.4.12.
Searched in the following locations:
    file:/C:/Users/udayv/AppData/Local/Android/Sdk/extras/m2repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.pom
    file:/C:/Users/udayv/AppData/Local/Android/Sdk/extras/m2repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar
    file:/C:/Users/udayv/AppData/Local/Android/Sdk/extras/google/m2repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.pom
    file:/C:/Users/udayv/AppData/Local/Android/Sdk/extras/google/m2repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar
    file:/C:/Users/udayv/AppData/Local/Android/Sdk/extras/android/m2repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.pom
    file:/C:/Users/udayv/AppData/Local/Android/Sdk/extras/android/m2repository/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar
    https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.pom
    https://dl.google.com/dl/android/maven2/org/codehaus/groovy/groovy-all/2.4.12/groovy-all-2.4.12.jar
Required by:
    project :app > com.android.tools.lint:lint-gradle:26.2.1

**Comment by deltatoken** [comment]
simply change the app lvl build gradle and top lvl build gradle as such : 
app lvl build gradle :
apply plugin: 'com.android.application'


    compileSdkVersion 28
    buildToolsVersion '28.0.3'
    defaultConfig {
        applicationId "jwtc.android.chess"
        minSdkVersion 14
        targetSdkVersion 28
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    lintOptions {
        disable 'MissingTranslation'
    }
}

dependencies {
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:mediarouter-v7:28.0.0'
    implementation 'com.google.android.gms:play-services-cast:16.2.0'
    implementation 'com.google.android.gms:play-services-analytics:16.0.8'
    implementation 'org.codehaus.groovy:groovy-all:2.4.12'

}

apply plugin: 'com.google.gms.google-services'


aand in the top lvl build gradle -----:


// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        jcenter()
        mavenLocal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath 'com.google.firebase:perf-plugin:1.2.1'
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31'
    }
}

allprojects {
    repositories {
        //mavenLocal() must be listed at the top to facilitate testing
        mavenLocal()
        google()
        jcenter()
    }
}

**Comment by jcarolus** [comment]
Latest master tagged 8.9.5 had Gradle upgrade which fixes the issue for me. Let me know if it does not work, closing.
