### ISSUE TITLE
Reading position gets lost after device orientation changes

### ISSUE THREAD

**Issue by geniuslittleteddy** [jcarolus/android-chess#129]
Please see the pics before and after device rotation

![Screen Shot 2020-08-17 at 11 25 49 PM](https://user-images.githubusercontent.com/67744580/90413526-29192a80-e0e1-11ea-8e76-d2c649665e51.png)
![Screen Shot 2020-08-17 at 11 25 56 PM](https://user-images.githubusercontent.com/67744580/90413529-2a4a5780-e0e1-11ea-8ce9-df241a6c7a5b.png)

**Comment by jcarolus** [comment]
The app is currently designed only for portrait view.
This may change in the future.
