### ISSUE TITLE
error(?)

### ISSUE THREAD

**Issue by nnantsop** [jcarolus/android-chess#132]
Good evening, I am an IT student from Greece and I had to study and understand a code, that may have some faults, so I decided to read a code about chess since I know how to play. When I was running your code I identified some points that I would change. First of all, the user decides what colour the pone will be, meaning the user decides if he plays first or second while the turn of moves should be randomly. Secondly, when  the user plays against PC he doesn't have the option of "draw" or "resign", an option that he has in a real game of chess. Finally, the PC mustn't lose from the user, but I could beat it, so your code could have some improvements. However, you have made an excellent application.

**Comment by 20captainx12** [comment]
>  the PC mustn't lose from the user
Then what's the point of playing?

**Comment by jcarolus** [comment]
Will close this issue.
The Play option indeed misses this way to end the game, but that is intentional, not an error.
