### ISSUE TITLE
Analysis and Metrics

### ISSUE THREAD

**Issue by grigange** [jcarolus/android-chess#136]
Hello, I am a student from Greece studying CS, I used Metrics Tools and I am going to share the results I found as part of a project I have in a course.
I have found some problematic classes with high Complexity and Size:

- ICSClient
- ChessView
- GameControll
- ICSChessView
- main
- ICSServer

You can see my full analysis here: [https://docs.google.com/document/d/1sqDY5v3HnenaXBT12BgYwCPOKZ3KAHtx6Jd_DC05fFQ/edit?usp=sharing](url)

**Comment by jcarolus** [comment]
Thanks for your message.
By coincidence, i have started some refactoring to improve the code and merged that to master branch today.
Curious how this will affect the report.
