### ISSUE TITLE
Black Pawns don't show up nor do the coordinates

### ISSUE THREAD

**Issue by KDesp73** [jcarolus/android-chess#152]
They are both there but  appear completely blank

![chess_screenshot](https://user-images.githubusercontent.com/63654361/211649269-256ad5bc-a66d-4a2d-aa12-8a3f8891d2b8.jpg)

**Comment by KDesp73** [comment]
Android version 11 and yes it was downloaded from Play Store. I just pressed Play

**Comment by jcarolus** [comment]
1. what happens when you set the Chess board preferences to show coordinates? (by default, they are turned off).
2. do you have "Night mode" turned on in Android settings (outside the Chess app)? If so, what happens if you turn it off?

**Comment by KDesp73** [comment]
When you set coordinates on only a white rectangle appears in their place.
Yes the issue apprears to be android's dark mode. With light mode both black pawns and coordinates work just fine.

**Comment by jcarolus** [comment]
Do your settings use color inversion? see:
https://support.google.com/accessibility/android/answer/6151800?hl=en
Can you check with that inversion turned off?

Not sure if I can programmatically prevent this from happening; the images for the pieces are actually black, and coordinate text is also black. Also it's unclear why it only applies it to the pawns.

**Comment by KDesp73** [comment]
Color inversion is off. Also in other piece sets ("California" for example) the issue appears in all the pieces, not just the pawns. On the other hand the "Kosal" set works perfectly.

**Comment by jcarolus** [comment]
So maybe even without this color inversion, the night mode is still somehow trying to be smart.
Difference with the "Kosal" is that these are a just a bit lighter than black. Maybe that is a solution, to make the other piece the same black as Kosal.
Anyway - thanks for reporting. Perhaps i will give this color replacement a go.

**Comment by KDesp73** [comment]
No problem!
