### ISSUE TITLE
Chess960 castling problem

### ISSUE THREAD

**Issue by heuchi** [jcarolus/android-chess#156]
Starting pos: #425
[Event "?"]
[Site "?"]
[Round "?"]
[White "Unbekannt"]
[Black "Unbekannt"]
[Variant "Fischerandom"]
[Setup "1"]
[FEN "rnqbbnkr/pppppppp/8/8/8/8/PPPPPPPP/RNQBBNKR w KQkq - 0 1"]
1. d4 h5 2. e4 d6 3. Ne3 Ne6 4. c3 c5 5. d5 Ng5 6. Qc2 Nh7 7. c4 f6 8. f3 O-O 9. Nc3 Na6 10. a3 e6 11. dxe6 Qxe6 12. Bg3 f5 13. Nxf5 h4 14. Bf2 Bg6 15. Nxh4 Bxh4 16. Bxh4 Qxc4 17. Be2 Qe6 18. Rd1 Nc7 19. Nb5 Bxe4 20. fxe4 Qh6 21. Bc4+ Ne6 22. Rxd6 Qxh4 23. Bxe6+ Kh8 

I can't enter 24. O-O now. I guess the problem is, that f1 is attacked. But as far as I understand, that shouldn't be a problem and castling is legal in this position.

**Comment by jcarolus** [comment]
Thanks for reporting this. Will have a look at it.

**Comment by jcarolus** [comment]
@heuchi the fix will be available in version 9.3.15 which is now being released in the Chess open testing track of the Play store.
