### ISSUE TITLE
i want to change difficulty of AI which part of code deals with it

### ISSUE THREAD

**Issue by aakash2731** [jcarolus/android-chess#157]

**Comment by jcarolus** [comment]
The implementation of the engine is located in
https://github.com/jcarolus/android-chess/tree/master/native/project/jni

The UI of difficulty settings is here
https://github.com/jcarolus/android-chess/blob/master/app/src/main/java/jwtc/android/chess/play/GameSettingsDialog.java

This is an old fashioned Engine and does not use any real AI, such as neural networks or the like.
