### ISSUE TITLE
I want to highlight legal moves for pieces (paid)

### ISSUE THREAD

**Issue by aakash2731** [jcarolus/android-chess#159]
I want to highlight legal moves can you contact to me via mail
Aakashgoel2070@gmail.com

I can pay you if you want or else please explain me which part of code deals with it

it will be of great help if you can mail though:)

**Comment by jcarolus** [comment]
So this was a feature in older versions when there was no drag and drop of pieces and no Duck chess.
Also it did not exist for online play, practice and puzzles.
So there are some building blocks available for this feature. 
Will get back to you when I have some time.

**Comment by aakash2731** [comment]
On Tue, 21 Nov 2023 at 1:55 PM, Jeroen Carolus ***@***.***>
wrote:

> So this was a feature in older versions when there was no drag and drop of
> pieces and no Duck chess.
> Also it did not exist for online play, practice and puzzles.
> So there are some building blocks available for this feature.
> Will get back to you when I have some time.
>


Please mail right now I am in need of that feature immediately

**Comment by jcarolus** [comment]
Can you indicate the following:
1. does it need to work in the Play section only, or also in the Play online section?
2. is there an application that can act as an example?

Perhaps I can then think of an approach and tell you where in the code to make the changes.

**Comment by aakash2731** [comment]
Similar to lichess

I need it done for both play and online mode

I have updated ui of your game to a much better version 10x better tbh but
unable to add legal moves highlighting

**Comment by jcarolus** [comment]
That sounds great. It's most likely most effective if you create a PR with your UI improvements first, so it can be based on top of that.

**Comment by aakash2731** [comment]
Can you Dm your WhatsApp number on

***@***.***

We can have a detailed discussion

**Comment by aakash2731** [comment]
![Uploading IMG_4204.png…]()
See these

**Comment by aakash2731** [comment]
Sure I would be interested however how can we communicate dude this way is really difficult

**Comment by jcarolus** [comment]
:) it is - gitbub even anonymizes your e-mail address, so that did not help...
jcarolus at gmail dot com
