### ISSUE TITLE
Chessnut Evo support?

### ISSUE THREAD

**Issue by sorsted** [jcarolus/android-chess#162]
Does this support Chessnut Evo yet?

**Comment by jcarolus** [comment]
Hi @sorsted 
No it is not, and this would be difficult to achieve. The engine is builtin the application is and not usable as a separate UCI engine.

**Comment by sorsted** [comment]
@jcarolus You do realize that the Chessnut Evo is simply an Android tablet with a built in chessboard on the side? The app can already run on the Evo as it is, it simply does not utilize the features of the board. I believe it would be quite simple to implement.
