### ISSUE TITLE
FICS random board flip

### ISSUE THREAD

**Issue by jcarolus** [jcarolus/android-chess#4]
The board flips at a random point in the game

**Comment by kiruwka** [comment]
is it still reproducible ?

**Comment by jcarolus** [comment]
Not sure. 
The original reporter of the bug did not give a lot of detail. But I have run into it once during development, if I am not mistaken after a rematch - which indicates a bug in keeping/cleaning state of the current game.
Currently I am doing work on the FICS client, so let me know if you want to have a look at it to avoid merge conflicts.

**Comment by kiruwka** [comment]
Thanks for replying.
I would like to add some little UI improvements - make it a bit more "material", I will start very small to avoid problems. Hope it is ok for you ?

**Comment by jcarolus** [comment]
That is great, pull requests are very welcome! 
UI can be improved a lot, and material design is an excellent standard that goes well with an app for chess. Depending on how much effort you want to put in this, we can create a separate issue to discuss if you like.

**Comment by bridgesense** [comment]
A material design sounds pretty cool!  Please count me in on the Beta test.  

In all honesty though, most chess app UI's for Android are horrible!  I look at some of the ones that have 4.0+ ratings and they don't have nearly the versatility or functionality this App does.  It is by far the best FICS Android GUI available and should have more recognition on freechess.org.  I migrated from Mobialia sheerly for the missing features this App has - like the ability to read chats during a FICS game.

The fact that the more advanced features in this app are hidden in drop downs is nice.  I've never felt intimidated by it.  I hope this APP's UI execution is preserved during the update.

**Comment by jcarolus** [comment]
I have created a new issue for this to discuss and update on it.
https://github.com/jcarolus/android-chess/issues/44
Let me know your thoughts.

**Comment by jcarolus** [comment]
closing this - not reproduced, too old.
