### ISSUE TITLE
Share Intent

### ISSUE THREAD

**Issue by bridgesense** [jcarolus/android-chess#45]
When viewing pgn files in a file browser, we have the ability to import the pgn file into the game database or play the pgn file directly.  It would be nice to also have a share intent registered for PGN files for both game import and play.

This allows us to easily share pgn or fen files from other apps like Asim Pereira's Chess Book Study or Analyze This and play them immediately in Chess without have to manually import a pgn file.

**Comment by jcarolus** [comment]
Good idea, and should be easy to implement.

**Comment by jcarolus** [comment]
Just updated develop branch with an extra intent filter for simple sharing.
Can you test if this works as expected with the other apps?

**Comment by bridgesense** [comment]
I shared a pgn file from both of the programs I mentioned above.  Chess was one of the share options labeled, "Play".  It worked perfectly.

Thanks!

**Comment by jcarolus** [comment]
Just published updated version to the play store.

**Comment by bridgesense** [comment]
Awesome!  A lot of great updates on this release.
