### ISSUE TITLE
enter/return on soft keyboard does not submit input anymore

### ISSUE THREAD

**Issue by smemsh** [jcarolus/android-chess#78]
since one or two releases ago, I can no longer do things like `accept<enter>` when someone challenges me to a rematch, because all `<enter>` does is add a new line to the input, without submitting.  this affects all console actions; I cannot submit any commands, such as "history" or "finger" because there is no way to submit the command, it just adds newlines.

I am using Google's keyboard from Market, which worked fine before.  Stock Android 5.0.2.  The game play still works, but any interaction using the telnet interface is impossible.

**Comment by jcarolus** [comment]
Thanks for posting. It should be fixed in the next update.

**Comment by smemsh** [comment]
seems fixed in latest release.  thanks.
