### ISSUE TITLE
change console / server output to use fixed width font for alignment

### ISSUE THREAD

**Issue by smemsh** [jcarolus/android-chess#79]
Nothing lines up in the console/output view.  They of course *do* line up using a fixed-width font, since the canonical interface is a terminal.  The app uses a variable-width font, however, so any output from the server looks like a total unaligned mess (example is 'history' or 'finger' output).

**Comment by smemsh** [comment]
This appears to be partially done with 26103bd3139d8df42f260f2e90acff9aff2950dd but that patch hardcodes the font size and it's way too large on my device, I get only 48 columns now (80 are needed for FICS output to appear sane).  See my comments on that patch: https://github.com/jcarolus/android-chess/commit/26103bd3139d8df42f260f2e90acff9aff2950dd#commitcomment-16604184

**Comment by TimmyT123** [comment]
Okay,  I'll look into it using different display screens.  Thanks.

**Comment by smemsh** [comment]
I don't know if these links are helpful, I found them when considering a try myself:

- http://stackoverflow.com/questions/4794484/calculate-text-size-according-to-width-of-text-area
- http://stackoverflow.com/questions/2617266/how-to-adjust-text-font-size-to-fit-textview

At some point I might attempt it, but will not have time for a while.  The program is still usable in the meantime...

**Comment by jcarolus** [comment]
Closing, PR with fix was merged.
