### ISSUE TITLE
"flag" menu item (to force win on time) causes resign instead

### ISSUE THREAD

**Issue by smemsh** [jcarolus/android-chess#82]
I've had this happen to me a few times now:

1. opponent player clock expires (I'll be winning on time)
2. for some reason auto-flag is not working
3. wonder what's going on, wait 20 seconds or so
4. select 'flag' option from menu (try to force it)
5. chess game actually resigns instead (wtf??)

I have had this happen to me a few times, and first thought I was imagining things, but now it's enough that I'm thinking it's a bug and the application incorrectly maps the flag menu to resign action.

**Comment by TimmyT123** [comment]
Hi Scott,
I definitely wouldn't be happy if my opponent flagged and 20 seconds later the game resigns me.  I would have to figure out how to get an emulator to lag (to work on it).  Jeroen would be better to find the answer to this.  If he doesn't have the time and you still get this, I will look into it.  I will check if flagging actually flags your opponent.

**Comment by TimmyT123** [comment]
Hi Scott,
You are correct!   You found a bug.  The flag option did not have a return and under it was the resign option.  It will be corrected in the next update.  Have a good day!

**Comment by smemsh** [comment]
the thing is, the server is the entity trust implements auto-flag, there's no reason a manual flag from the client should be necessary if it's set.  this makes me think it's actually a server bug.

I just noticed this from the help:

> When your opponent has extreme lag it appears as though they have run out of time, when in fact they haven't. Sometimes, it gets so bad, the opponent is disconnected from the server. In this case, autoflag won't work, and neitherwill  "flag". To end the game you need to "adjourn".

now I think this is probably someone unplugging their internet when they are going to lose on time.  Why the server can't handle it, I don't know... but having to know to ”adjourn” seems more than a little bizarre.

I don't know if android-chess could actually do anything about this... but certainly resigning is the wrong thing to do so there may be a lurking bug still, it's unclear.

I do know that I'll try ”adjourn” manually next time but this would be a really strange thing for android-chess to try automatically so I'm not sure if any action is really possible here.  I can't figure out why it would ever resign though unless there was a client bug somewhere, maybe thinking the game is in a different state than it really is.

**Comment by smemsh** [comment]
ok, well that answers that.  both problems solved! thanks.
