### ISSUE TITLE
abort request -> declined -> bad state, cannot play

### ISSUE THREAD

**Issue by smemsh** [jcarolus/android-chess#88]
I was tired of waiting for someone to make a move (this is after game started, a few moves in). So I sent an abort request.  Opponent declined.  

Suddenly, the board was reversed, my player (black) was on *top*, and the program did not think I was playing a game anymore (I.e. no resign or abort available in the menu, as if no current game).  Yet clock was ticking and it was my move 

I think perhaps the abort-declined code path needs a bit of scrutiny...

**Comment by TimmyT123** [comment]
Interesting.   It sounds like lag had something to do with it.   I'll try to recreate the scenario.   Thanks.

**Comment by smemsh** [comment]
if you want, I can match you right now and we can attempt reproduction.  send me an email with your username if you like

**Comment by TimmyT123** [comment]
Has it happened to you more than once?   I'll test it with emulators this weekend.   On fics, I am coconutone.

**Comment by TimmyT123** [comment]
Yes, good find.  Chess was automatically trying to close the game when an abort was offered.  It will be fixed in the next release.  Thank you.

**Comment by jcarolus** [comment]
Closing, the PR was merged.
