### ISSUE TITLE
Undo problem

### ISSUE THREAD

**Issue by smedic** [jcarolus/android-chess#98]
When playing against CPU, if it makes a move, and you do UNDO, you can control CPU's pieces, and you become CPU.

Steps:
1. Make a move (white)
2. CPU makes a move
3. press UNDO
4. Play with CPU's pieces
5. CPU plays with yours

**Comment by TimmyT123** [comment]
Hi Stevan,
To undo your last move, press the UNDO button twice (It will undo the CPU and your move.)
Sometimes I want the CPU to make a different move, especially the open move.
Steps:
1. Press UNDO
2. Make move for CPU.
3. CPU makes move for me.
4. Press UNDO
5. Make my move.

Also, you have the option of switching sides ,anytime in the game, by pressing UNDO once and pressing Flip board.

Have a good day!,
Tim

**Comment by jcarolus** [comment]
Hi Stevan,

This is indeed intended behaviour. Pressing the Play button will make the CPU do a move again.

Best regards,
Jeroen
